apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airdrawer
  namespace: airdrawer
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airdrawer
                port:
                  number: 80
